spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hermesafe_db}
    username: ${DB_USERNAME:hermesafe_user}
    password: ${DB_PASSWORD:hermesafe_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true